services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - otel-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 16686:16686
      - 14250:14250
      - "6831:6831/udp"
    networks:
      - otel-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - otel-network

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: otel-collector
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - --config=/etc/otel-collector-config.yaml
    ports:
      - 4317:4317
      - 4318:4318
      - 13133:13133
      - 8888:8888
      - 8889:8889
      - 55679:55679
      - 1888:1888
    restart: always
    depends_on:
      - opensearch
      - jaeger
      - prometheus
    environment:
      OPENSEARCH_LOGS_INDEX: "logs-stream"
      OPENSEARCH_HOST: opensearch:9200
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin
      OPENSEARCH_TLS_INSECURE: "true"
      OPENSEARCH_TLS_INSECURE_SKIP_VERIFY: "true"
    networks:
      - otel-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - otel-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - otel-network
networks:
  otel-network:
    driver: bridge
volumes:
  opensearch-data:
  grafana-storage:
